### PR TITLE
README: Fix install link

### PR DESCRIPTION
**Pull request by andys8**

### CODE REVIEW

**Comment by xtaran** [comment]
Thanks for the contribution, but that seems the wrong repo for such changes. This is the Debian packaging of qutebrowser, not qutebrowser itself. Please see https://github.com/qutebrowser/qutebrowser/pulls — but be aware that I think that this link is local on purpose as that way it also works offline in an unpacked qutebrowser source tar ball or git working directory, pointing to the included documentation in the sub directory `doc`

In case you really want that the Debian package's README contains a different install link than upstream's README:

Since one usually see this in the README file of the already installed package, this is a rather useless part of the README for an packaged version of qutebrowser, so I wouldn't change anything there except maybe to completely remove any installation instructions.

**Comment by The-Compiler** [comment]
FWIW the link is fine in the upstream repo - it's just that `doc/install.asciidoc` isn't packaged in releases because it's probably not needed there.

**Comment by andys8** [comment]
There is an "Installing" link at the top. It links to the main repository install file. That's why I did this change for the other link ;)

**Comment by xtaran** [comment]
> FWIW the link is fine in the upstream repo - it's just that `doc/install.asciidoc` isn't packaged in releases because it's probably not needed there.

Ah, that explains the issue. thanks. Nevertheless—and as state above—for the very same reason as well as if any change on upstream code would only be present in `debian/patches/`, updating it in this repo doesn't make sense. (@andys8: So thanks for closing it again.)

**Pull request closed without merging**
